### ISSUE TITLE
Refactor editing translatable fields

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#177]
The editing of translatable fields should be improved.

Particularly focus on the following aspects:

* [x] For mandatory fields make it possible to set only the default language to required [see #338].
  * [x] Make this the new default behaviour
  * [x] Add a helper method to control which languages are mandatory for easy customisation
* [x] Make implementation more elegant by actually mapping translation entities.
* [x] Verify that the form saves translated values properly. In 1.3.x submitting an invalid form caused a reload with all translations being empty [see #386].
* [x] Use tabs for translatable fields [see #834].
  * [x] Add an asterisk after the title of tabs for mandatory languages
  * [x] Update screenshot in documentation

**Comment by Guite** [comment]
The translatable extension has changed a bit which needs to be considered:
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md

**Comment by rallek** [comment]
Just for notice:
In our company we use sharepoint. There it is solved in another way. E.g. you have a site with German, French and English installed. You choose via locale block the german language. In this case you fill your translatable field in German. All languages are now filled with the German content after saving. Now you switch your site via locale block into french. You go to edit and see every translatable field filled in german. You may now want to translate to French. At the end you proceed the same way to English.

This is another way how to manage the translation workflow. 

I would prefere the current way. To be able to translate it in one step would be nice. To make a better overview you can toggle the other languages. It would be perfect if the other translation fields of the translatable field are pre filled with the first language content. But I think a reload is needed somehow.

**Comment by Guite** [comment]
Wondering whether this should be a blocker for 0.7.2 (probably causing a brief delay after Zikula 1.4.6 is final) or postponed to 0.7.3?

**Comment by rallek** [comment]
postpone it into 0.7.3. It is not functional important.

**Comment by Guite** [comment]
ok
