### ISSUE TITLE
[WIP] Convert JS from Prototype to jQuery and Bootstrap

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#238]
Rewrite all JavaScript elements using jQuery- and Bootstrap-based technologies.

Basic topics:
- [x] Naming JS files: done (37a8108014618c21c433d0eff6cf02cf35cdb9ff)
- [x] jQuery usage: https://github.com/zikula/core/issues/1041
- [x] New data-switch: https://github.com/zikula/core/issues/845#issuecomment-20919441
- [x] Lightbox replacement by phaidon
- [x] Tabs: http://zikula.github.io/bootstrap-docs/javascript/#tabs
- [x] Panels: http://zikula.github.io/bootstrap-docs/components/#panels
  - [x] Collapse: http://zikula.github.io/bootstrap-docs/javascript/#collapse
- [x] HTML5 Validation

Advanced topics:
- [x] Context menus (done in c843641ac076d11000f383190a75f6bc184835dd)
- [x] Auto completion using Bootstrap-3-Typeahead (done in db317442d27f771ee6ab58b696467b15e86a3cd8)
- [x] Tree: https://github.com/zikula/core/issues/1752 (done in 555e10932609917153e6377eeab794a9e22b85a5)
- [x] Window widgets: https://github.com/zikula/core/issues/1761 (done in 4fd5ec6a8be60179266b48d9c6e2a799b449cc5e)

Misc:
- [x] Update changelog (done in https://github.com/Guite/MostHelp/commit/b4623c0cecd9b81e6be42065102297f0c20f177d and https://github.com/Guite/MostLocales/commit/ca3f7c194c6050f88fcd24e063bce4fc3e1af16f)
